name: Sync to Hugging Face Hub
on:
  push:
    branches: [feat/WhaleAlerts] # Chạy khi bạn push vào nhánh main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true # Nếu bạn có file lớn

      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          if [ -z "$HF_TOKEN" ]; then
            echo "Error: HF_TOKEN is empty! Please check your GitHub Repository Secrets."
            exit 1
          fi
          
          # 1. Xóa toàn bộ lịch sử Git cũ để HF không bắt lỗi file nhị phân trong quá khứ
          rm -rf .git
          git init
          git branch -M main
          
          # Cấu hình Git
          git config --global user.email "KimNhuong@gmail.com"
          git config --global user.name "Kim Nhuong"
          
          # 2. Xóa hẳn file .png ở thư mục làm việc và tạo 1 commit mới hoàn toàn sạch sẽ
          rm -f docs/*.png || true
          
          # 3. Ghi đè file Dockerfile gốc bằng cấu hình dành riêng cho Hugging Face
          cp Dockerfile.spark-hf Dockerfile
          
          git add .
          git commit -m "Deploy fresh state to Hugging Face without binary history"
          
          # Thêm remote HF và push
          # Thay 'username/space-name' đúng với cái bạn tạo trên HF
          git push --force https://DK123bk:$HF_TOKEN@huggingface.co/spaces/DK123bk/DockerSpark main:main